/* @format */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import dayjs from 'dayjs'
import { getAllEvents } from 'libs/client'
import Header from 'components/Header'
import styles from 'styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ events }) {
    return (
        <>
            <Head>
                <title>BRANZコンシェルジュのお知らせ</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header title="今後のイベントスケジュール"></Header>
                <ul className={styles.lists}>
                    {events.map((event) => (
                        <li key={event.id}>
                            <p>{dayjs(event.date).format('YYYY年M月DD日')}</p>
                            <h2>{event.title}</h2>
                            {event.categories && event.categories.length > 0 && (
                                <p>{event.categories.map((cat) => cat.name).join(', ')}</p>
                            )}
                        </li>
                    ))}
                </ul>
            </main>
        </>
    )
}

export const getStaticProps = async () => {
    const events = await getAllEvents(10)

    return {
        props: {
            events,
        },
    }
}
