/* @format */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import dayjs from 'dayjs'
import { getAllEvents, getBasicInfo } from 'libs/client'
import Header from 'components/Header'
import Info from 'components/Info'
import styles from 'styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ events, basicInfo }) {
    return (
        <>
            <Head>
                <title>BRANZコンシェルジュのお知らせ</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.container} stack-lg`}>
                <Header title="今後のイベントスケジュール"></Header>
                <ul>
                    {events.map((event) => (
                        <li key={event.id} className={styles.list}>
                            <p className={styles.eventDate}>{dayjs(event.date).format('M月DD日(ddd)')}</p>
                            <h2 className={styles.eventName}>{event.title}</h2>
                            {event.categories && event.categories.length > 0 && (
                                <p>{event.categories.map((cat) => cat.name).join(', ')}</p>
                            )}
                        </li>
                    ))}
                </ul>
                <footer className={styles.footer}>
                    <div className={styles.banner}>
                        {basicInfo.banner && (
                            <Image
                                src={basicInfo.banner.url || basicInfo.banner}
                                alt={basicInfo.title || 'インフォメーション'}
                                width={basicInfo.banner.width}
                                height={basicInfo.banner.height}
                                layout="responsive"
                            />
                        )}
                    </div>
                    <Info detail={basicInfo}></Info>
                </footer>
            </main>
        </>
    )
}

export const getStaticProps = async () => {
    const events = await getAllEvents(10)
    const basicInfo = await getBasicInfo()

    return {
        props: {
            events,
            basicInfo,
        },
    }
}
